const LOAD_EVENT = 'LOAD_EVENT';
const ADD_EVENT = 'ADD_EVENT';
const SET_EVENT = 'SET_EVENT';
const DEL_EVENT = 'DEL_EVENT';
const ADD_CHILD_EVENT = 'ADD_CHILD_EVENT';
const SET_CHILD_EVENT = 'SET_CHILD_EVENT';
const DEL_CHILD_EVENT = 'DEL_CHILD_EVENT';
const SET_LANG = 'SET_LANG';
const SET_CURRENCY = 'SET_CURRENCY';

export { LOAD_EVENT, ADD_EVENT, DEL_EVENT, ADD_CHILD_EVENT, SET_EVENT, SET_LANG, SET_CURRENCY, SET_CHILD_EVENT, DEL_CHILD_EVENT };